---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install common dependencies
  package:
    name:
      - curl
      - wget
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
    state: present
