apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default  # Replace with your namespace if needed
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
