apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default  # Replace with your namespace if needed
subjects:
  - kind: ServiceAccount
    name: pod-reader-sa
    namespace: default  # Replace with your namespace if needed
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
