apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  clusterIP: None  # This makes the service headless for StatefulSet
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
